### ISSUE TITLE
Not remembering channels between restarts

### ISSUE THREAD

**Issue by duncan-bayne** [DanielOaks/oragono#104]
Perhaps I'm missing something simple here, but if I take the following steps:

1. Install oragono.
2. Connect.
3. Create a channel with `/join foo`, and set the topic with `/topic bar`.
4. Verify the channel `#foo` is present with `/list`; I see the channel and the topic.
5. Restart oragono.
6. Connect.
7. Issue `/list`, and this time I _don't_ see the channel `#foo`.
8. Issue `/join foo`, and receive a message that channel `#foo` has been created.

I'd expect knowledge of the channel to persist between restarts.  I suspect that I'm misunderstanding something about IRC, oragono, or both.

**Comment by DanielOaks** [comment]
Hey Duncan, thanks for the issue!

Channels are totally reset when the server restarts, unless they're registered. If you register a channel then any modes set on it, the topic, and the fact that you're the channel founder are remembered across restarts.

To register a channel, what you'll do is:

1. Register your account with `/quote ACC REGISTER <username> * passphrase :<password>`
2. Join the channel with `/join #channel`
3. Register the channel with `/privmsg ChanServ REGISTER #channel

Once this is done, any topic/mode changes should be remembered on the channel. After this you'll also want to setup SASL on your client (with the username and password given in step 1) so that you login whenever you connect to the server again. Freenode provides steps for setting up SASL here: https://freenode.net/kb/answer/sasl

However, the channel doesn't actually exist until you join it. When a channel's registered, it just means that the details are remembered in the background, and if someone joins it then the channel is created with those specific details (so doing `/list` right after joining won't show any channels). I might look at a command to show all the registered channels though, particularly for opers and similar.

This is the same across different IRC servers -- unless you register the channel with ChanServ or some other similar trick, they're always forgotten on restarts. Thanks for trying out oragono, feel free to yell with how this goes or anything else you run into!

**Comment by DanielOaks** [comment]
I'll mark this as fixed for now, we've documented this a bit better in the readme and all. Thanks again for the yell!
